name: Deploy Chatbot Page

on:
  push:
    branches:
      - main  # Exécute ce workflow à chaque push sur la branche principale.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Node.js pour les dépendances et la construction
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Assurez-vous d'utiliser une version compatible avec vos outils

      # Installer les dépendances (si nécessaire)
      - name: Install dependencies
        run: npm install

      # Créer le répertoire `docs` s'il n'existe pas
      - name: Create docs directory if missing
        run: mkdir -p docs

      # Injecter le token Hugging Face dans un fichier sécurisé
      - name: Inject Hugging Face Token
        run: echo "const HUGGINGFACE_TOKEN = '${{ secrets.HUGGINGFACE_TOKEN }}';" > docs/token.js

      # Construire le projet si nécessaire (remplacez cette étape si vous avez une commande de build spécifique)
      - name: Build project
        run: npm run build

      # Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
