name: Deploy Chatbot Page

on:
  push:
    branches:
      - main  # Exécute ce workflow à chaque push sur la branche principale.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create docs directory if missing
        run: mkdir -p docs

      - name: Inject Hugging Face Token
        run: echo "const HUGGINGFACE_TOKEN = '${{ secrets.HUGGINGFACE_TOKEN }}';" > docs/token.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Utilise le token PAT ici
          publish_dir: ./docs
