name: Deploy Chatbot

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the public repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Set up Node.js for JavaScript (required to run app.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the appropriate Node.js version

      # Step 5: Inject the API key as an environment variable
      - name: Inject Chatbot API Key
        run: |
          echo "CHATBOT_API_KEY=${{ secrets.CHATBOT_API_KEY }}" >> $GITHUB_ENV

      # Step 6: Install Node.js dependencies (if you have a package.json)
      - name: Install Node.js dependencies
        run: |
          npm install

      # Step 7: Run the JavaScript application
      - name: Run app
        run: node app.js
