name: Deploy Chatbot Page

on:
  push:
    branches:
      - main  # Exécute ce workflow à chaque push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Créer le répertoire 'docs' s'il manque
      - name: Create docs directory if missing
        run: mkdir -p docs

      # Étape 3 : Injecter le Hugging Face Token dans un fichier JavaScript
      - name: Inject Hugging Face Token
        run: echo "const HUGGINGFACE_TOKEN = '${{ secrets.HUGGINGFACE_TOKEN }}';" > docs/token.js

      # Étape 4 : Déployer vers GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Utilisation du secret GH_TOKEN pour l'authentification
          publish_dir: ./docs  # Le répertoire à publier sur GitHub Pages
